---
# tasks file for ansible-ssh
- name: Install openssh
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
    - openssh-server
- name: Start sshd service
  become: true
  ansible.builtin.systemd:
    name: sshd
    state: started
- name: Setup authorized_key
  ansible.posix.authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ public_key_path }}"
- name: Config ssh config
  ansible.builtin.import_tasks: config.yml
  become: true
- name: Disable sudo password
  ansible.builtin.import_tasks: disable-sudo-password.yml
  become: true
