---
# tasks file for ansible-ssh
- name: create .ssh directory
  file: path=~/.ssh state=directory mode=0700
  tags:
    - insert_key
- name: copy ansible key
  copy: src="{{public_key.path}}" dest="~/.ssh/authorized_keys" mode=0600
  register: result
  notify:
    # - restart sshd
    - disable password login
  tags:
    - insert_key
- name: disable root login
  become: true
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    backrefs: yes
  notify:
    - restart sshd
- name: comment ssh_host_dsa_key
  become: true
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^HostKey /etc/ssh/ssh_host_dsa_key'
    line: '#HostKey /etc/ssh/ssh_host_dsa_key'
    backrefs: yes
  notify:
    - restart sshd
- name: comment ssh_host_ecdsa_key
  become: true
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^HostKey /etc/ssh/ssh_host_ecdsa_key'
    line: '#HostKey /etc/ssh/ssh_host_ecdsa_key'
    backrefs: yes
  notify:
    - restart sshd
