---
# tasks file for ansible-ssh

- name: setup authorized_key
  authorized_key:
    user: "{{ansible_user_id}}"
    key: "{{public_key_path}}"
  notify:
    - disable password login
- import_tasks: config.yml
  become: true
- import_tasks: disable-sudo-password.yml
  become: true
  when: no_sudo_pass
