---
# handlers file for ansible-ssh
- name: disable password login
  become: true
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
    validate: 'sshd -f %s -T'
    backrefs: yes
  notify:
    - restart sshd
- name: restart sshd
  become: true
  systemd:
    name: sshd
    state: restarted
