---
# handlers file for ansible-ssh
- name: disable password login
  become: true
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
    backrefs: yes
  notify:
    - restart sshd
- name: restart sshd
  become: true
  service: name=sshd state=restarted
