---
- name: Converge
  hosts: all
  vars:
    ansible_user: ansible
  roles:
    - role: finaldes.ansible_ssh
      become: true
      restrict_key_exchange: false
      public_key_path: 'https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub'
  # tasks:
  # - name: install sshaudit
  #   pip:
  #     name: ssh-audit
