---
- name: Converge
  hosts: all
  vars:
    ansible_user: ansible
  roles:
  - name: "ansible-ssh"
    become: true
    public_key_path: 'https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub'
  tasks:
  - name: install sshaudit
    pip:
      name: ssh-audit
