---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu22.04
    image: finaldes/docker-ubuntu-ansible:jammy-20230215
    pre_build_image: true
    cgroupns_mode: host
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
  - name: ubuntu20.04
    image: finaldes/docker-ubuntu-ansible:focal-20230215
    pre_build_image: true
    cgroupns_mode: host
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
  # - name: ubuntu18.04
  #   image: finaldes/docker-ubuntu-ansible:bionic-20230215
  #   pre_build_image: true
  #   cgroupns_mode: host
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   privileged: true
  # - name: ubuntu16.04
  #   image: finaldes/docker-ubuntu-ansible:xenial-20200326_2
  #   pre_build_image: true
  #   command: ""
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: true
  # - name: instance
  #   image: docker.io/pycontribs/centos:7
  #   pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
