name: Ansible-Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - test
      - create-workflow/*
jobs:
  test:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        # version:
        #   - "stable"
        #   - "edge"
        #   - "test"
        #   - "nightly"
        os:
          - ubuntu-24.04
          - ubuntu-22.04
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v4.2.2
        # with:
        #   path: molecule_demo
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{matrix.python-version}}
      - uses: actions/cache@v4.2.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: set ansible config
        run: printf '[defaults]\nroles_path=../' >ansible.cfg
      - name: Install ansible dependencies
        run: ansible-galaxy install -r requirements.yml
      - name: check yaml linting
        run: yamllint .
      - name: check ansible lint
        run: ansible-lint
      - name: ansible syntax-check
        run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check
      - name: molecule test
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
